# Generated by Django 4.1.5 on 2023-01-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=2048)),
                ('new_url', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='qrcodes')),
            ],
        ),
    ]
